//This file is generated by bin/hook.js
var _ = require('underscore');
module.exports = {

  CSS: {
    
      'clappr_dash': '[data-html5-video]{position:absolute;height:100%;width:100%;display:block}',
    
  }
};
